MAIN = 'https://stellarburgers.nomoreparties.site/'
MAIN_BASE = 'https://stellarburgers.nomoreparties.site'
REGISTER =  f'{MAIN_BASE}/register'
LOGIN =  f'{MAIN_BASE}/login'
PROFILE = f'{MAIN_BASE}/account/profile'
RECOVERY = f'{MAIN_BASE}/forgot-password'